name: myaniapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^6.3.0
  shared_preferences: ^2.1.0
  hooks_riverpod: ^2.2.2
  riverpod_annotation: ^2.0.2
  uni_links: ^0.5.1
  flutter_hooks: ^0.18.6
  url_launcher: ^6.1.10
  graphql_flutter: ^5.1.2
  cached_network_image: ^3.2.3
  markdown_widget: ^2.1.0
  html: ^0.15.2
  markdown: ^7.0.2
  intl: ^0.18.0
  timeago: ^3.4.0
  dropdown_search: ^5.0.6
  holding_gesture: ^1.1.0
  contextmenu: ^3.0.0
  youtube_player_iframe: ^4.0.4
  workmanager: ^0.5.1
  flutter_local_notifications: ^14.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6
  graphql_codegen: ^0.12.0-beta.18

flutter:
  uses-material-design: true
