name: mygraphql
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.3.1 <4.0.0"

# Add regular dependencies here.
# path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
dependencies:
  flutter:
    sdk: flutter
  gql_dedupe_link: ^2.0.3
  gql: ^1.0.0
  gql_exec: ^1.0.0
  gql_link: ^1.0.0
  http: ^1.2.1
  normalize: ^0.9.1
  gql_http_link: ^1.1.0
  gql_transform_link: ^1.0.0
  gql_error_link: ^1.0.0+1
  flutter_hooks: ^0.20.5
  hive: ^2.2.3
