name: Build and Release Linux

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Linux App
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
          cache: true

      - name: Download deps
        run: |
          sudo apt update
          sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev libmpv-dev mpv

      - run: flutter pub get
      - run: flutter build linux

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: MyAniApp-linux-x64.zip
          directory: build/linux/x64/release/bundle

      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/linux/x64/release/bundle/MyAniApp-linux-x64.zip'
          allowUpdates: true
          makeLatest: true
